use_frameworks!

platform :ios, '8.0'

target 'TTCoverView_Example' do
  pod 'TTCoverView', :path => '../'

  target 'TTCoverView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
